### ISSUE TITLE
Release package on PyPI

### ISSUE THREAD

**Issue by fkromer** [BrickFrog/kedro-pandas-profiling#7]
Would be great if you could provide the package on [PyPI](https://pypi.org/). For info about how to test packaging you can refer to e.g. [using TestPyPI](https://packaging.python.org/guides/using-testpypi/). Let me know in case you need help.

**Comment by brickfrog** [comment]
I think I got it, I ended up switching everything to Github actions. A lot of Azure DevOps was a bit too clunky for this more simple use case.

Have it set to auto-release to PyPI on releases at the moment.

**Comment by fkromer** [comment]
The package is available on [pypi](https://pypi.org/project/kedro-pandas-profiling/). Thx.
